### ISSUE TITLE
网盘内已经有重名文件上传BUG

### ISSUE THREAD

**Issue by liupan1890** [qingzhenyun/qingzhenyun-api-doc#14]
在上传文件时，如果网盘内已经有重名文件

qingzhenyun-api-doc-master\zh-CN\v3\20.文件\050.获取上传地址.md

里  op  	| int 	|  是  	|  指示文件重复的时候采取何种操作

当尝试提交参数把op设置为2时（如果文件存在则覆盖），

可以正确获得上传token
可以正常makeblock和上传
但最后makefile时（合并文件时），会返回错误FILE_ALREADY_EXISTS------这是不正确的，应该覆盖

还有一次测试时是可以正常合并文件返回正确的数据，但是网盘内文件并没有刷新还是旧文件，没有被覆盖

如果不设置op参数，（默认为0 如果文件存在则报错？？）
就不可以正确获得上传token，直接报错

所以我现在只能先删除文件再上传文件

**Comment by liupan1890** [comment]
就是说覆盖操作有问题，没有正确覆盖

**Comment by qingzhenyun** [comment]
这个问题已经提交到技术部门。
________________________________
发件人: liupan1890 <notifications@github.com>
发送时间: 2020年8月18日 13:10
收件人: qingzhenyun/qingzhenyun-api-doc <qingzhenyun-api-doc@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [qingzhenyun/qingzhenyun-api-doc] 网盘内已经有重名文件上传BUG (#14)


在上传文件时，如果网盘内已经有重名文件

qingzhenyun-api-doc-master\zh-CN\v3\20.文件\050.获取上传地址.md

里 op | int | 是 | 指示文件重复的时候采取何种操作

当尝试提交参数把op设置为2时（如果文件存在则覆盖），

可以正确获得上传token
可以正常makeblock和上传
但最后makefile时（合并文件时），会返回错误FILE_ALREADY_EXISTS------这是不正确的，应该覆盖

还有一次测试时是可以正常合并文件返回正确的数据，但是网盘内文件并没有刷新还是旧文件，没有被覆盖

如果不设置op参数，（默认为0 如果文件存在则报错？？）
就不可以正确获得上传token，直接报错

所以我现在只能先删除文件再上传文件

―

**Comment by liupan1890** [comment]
感谢回复
