### ISSUE TITLE
21.新文件\020.获取文件信息.md 无效？

### ISSUE THREAD

**Issue by liupan1890** [qingzhenyun/qingzhenyun-api-doc#16]
qingzhenyun-api-doc-master\zh-CN\v3\21.新文件\020.获取文件信息.md

尝试通过***POST*** ***/v3/newfile/get***
读取文件信息，总是返回文件不存在的错误

**Comment by qingzhenyun** [comment]
请勿使用该接口，该接口在灰度环境。
________________________________
发件人: liupan1890 <notifications@github.com>
发送时间: 2020年8月18日 13:43
收件人: qingzhenyun/qingzhenyun-api-doc <qingzhenyun-api-doc@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [qingzhenyun/qingzhenyun-api-doc] 21.新文件\020.获取文件信息.md 无效？ (#16)


Closed #16<https://github.com/qingzhenyun/qingzhenyun-api-doc/issues/16>.

―
