### ISSUE TITLE
新文件和新回收站的替代问题

### ISSUE THREAD

**Issue by liupan1890** [qingzhenyun/qingzhenyun-api-doc#18]
发现

有文件和新文件
有回收站和新回收站

主要是api的路径不同，/v3/trashCan/list/  ----->/v3/newtrash/list

那么问题来了，
1 现在新文件的/v3/newfile/get 我测试无效，是只有这一个还是大部分新xx都无效？但是新回收站列文件api有效
这让人很混乱啊，想全部用新的，不能用。

2 原有的什么时候失效？还是会一直有效？

**Comment by liupan1890** [comment]
原来是所有的新都不能用，明白了

**Comment by qingzhenyun** [comment]
原有api继续有效的，暂时不会下线，新接口在预发布环境，请勿用于线上
________________________________
发件人: liupan1890 <notifications@github.com>
发送时间: 2020年8月18日 13:28
收件人: qingzhenyun/qingzhenyun-api-doc <qingzhenyun-api-doc@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [qingzhenyun/qingzhenyun-api-doc] 新文件和新回收站的替代问题 (#18)


发现

有文件和新文件
有回收站和新回收站

主要是api的路径不同，/v3/trashCan/list/ ----->/v3/newtrash/list

那么问题来了，
1 现在新文件的/v3/newfile/get 我测试无效，是只有这一个还是大部分新xx都无效？但是新回收站列文件api有效
这让人很混乱啊，想全部用新的，不能用。

2 原有的什么时候失效？还是会一直有效？

―

**Comment by qingzhenyun** [comment]
新文件非生产环境 请勿使用
________________________________
发件人: liupan1890 <notifications@github.com>
发送时间: 2020年8月18日 13:28
收件人: qingzhenyun/qingzhenyun-api-doc <qingzhenyun-api-doc@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [qingzhenyun/qingzhenyun-api-doc] 新文件和新回收站的替代问题 (#18)


发现

有文件和新文件
有回收站和新回收站

主要是api的路径不同，/v3/trashCan/list/ ----->/v3/newtrash/list

那么问题来了，
1 现在新文件的/v3/newfile/get 我测试无效，是只有这一个还是大部分新xx都无效？但是新回收站列文件api有效
这让人很混乱啊，想全部用新的，不能用。

2 原有的什么时候失效？还是会一直有效？

―
