### ISSUE TITLE
v3\20.文件\100.如何搜索文件.md 返回结果预期不一致

### ISSUE THREAD

**Issue by liupan1890** [qingzhenyun/qingzhenyun-api-doc#19]
qingzhenyun-api-doc-master\zh-CN\v3\20.文件\100.如何搜索文件.md
根据文档测试查询

```POST``` ```/v3/files/list/```

```json
{
	"parentIdentity": "::all",
	“name”:"EP"
}
```

会在/目录下所有文件中查找  EP  （包含所有子文件夹里面的所有文件）

```POST``` ```/v3/files/list/```

```json
{
	"parentIdentity": "/dirname",
	“name”:"EP"
}
```

会在/dirname目录下所有文件中查找  EP  （不包含所有子文件夹里面的所有文件）

不知道你是怎么设计的，
/就全部文件都找包括子文件夹，
/dirname就只查找文件，不包括子文件夹

同一个接口查找方式并不一致，返回结果根本不符合预期

普遍意义上的查找，自然是找/dirname下面的所有文件，包括子文件夹才对。比如windows资源管理器，

如果不需要查找子文件夹，我直接列/dirnam目录然后循环匹配就好了，查找功能就应该是包括子文件夹

如上，请修正此功能的实现

**Comment by liupan1890** [comment]
正常的应该是，判断请求参数有没有name

有name就是查找，包括子文件夹

没有name就是列目录

多么简单的事，程序怎么这么多低级错误

**Comment by qingzhenyun** [comment]
这个应该是一个兼容性问题，老接口于不仅仅承担搜索业务。
关于搜索近期应该有新的API提供。
________________________________
发件人: liupan1890 <notifications@github.com>
发送时间: 2020年8月19日 11:36
收件人: qingzhenyun/qingzhenyun-api-doc <qingzhenyun-api-doc@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [qingzhenyun/qingzhenyun-api-doc] v3\20.文件\100.如何搜索文件.md 返回结果预期不一致 (#19)


正常的应该是，判断请求参数有没有name

有name就是查找，包括子文件夹

没有name就是列目录

多么简单的事，程序怎么这么多低级错误

―

**Comment by liupan1890** [comment]
那就快点上线啊，api又不是硬件，2小时足够你开发+测试+上线了，，我看这个文档都上传了多长时间了，还一堆问题，真让人捉急，你以为程序猿是小学生吗？？？

**Comment by qingzhenyun** [comment]
这事您得怪懂王 :)
作为网络传输公司，公司有限的人力目前投入到应对中美光缆可能连接中断、甚至面临更大困难局面的应对上。目前对非盈利项目人力支持尚不足。
________________________________
发件人: liupan1890 <notifications@github.com>
发送时间: 2020年8月20日 11:16
收件人: qingzhenyun/qingzhenyun-api-doc <qingzhenyun-api-doc@noreply.github.com>
抄送: qingzhenyun <qingzhenyun@hotmail.com>; Comment <comment@noreply.github.com>
主题: Re: [qingzhenyun/qingzhenyun-api-doc] v3\20.文件\100.如何搜索文件.md 返回结果预期不一致 (#19)


那就快点上线啊，api又不是硬件，2小时足够你开发+测试+上线了，，我看这个文档都上传了多长时间了，还一堆问题，真让人捉急，你以为程序猿是小学生吗？？？

―

**Comment by qingzhenyun** [comment]
能否私信联系方式以便联系？我们的邮箱是qingzhenyun@hotmail.com
________________________________
发件人: liupan1890 <notifications@github.com>
发送时间: 2020年8月20日 11:16
收件人: qingzhenyun/qingzhenyun-api-doc <qingzhenyun-api-doc@noreply.github.com>
抄送: qingzhenyun <qingzhenyun@hotmail.com>; Comment <comment@noreply.github.com>
主题: Re: [qingzhenyun/qingzhenyun-api-doc] v3\20.文件\100.如何搜索文件.md 返回结果预期不一致 (#19)


那就快点上线啊，api又不是硬件，2小时足够你开发+测试+上线了，，我看这个文档都上传了多长时间了，还一堆问题，真让人捉急，你以为程序猿是小学生吗？？？

―
