### ISSUE TITLE
请回复一下现在的限速策略

### ISSUE THREAD

**Issue by liupan1890** [qingzhenyun/qingzhenyun-api-doc#22]
请回复一下现在的限速策略

#### 使用环境：
网页版点击下载，复制下载链接，使用IDM下载，并设置IDM为5线程并发下载，一次只下载一个文件！（特别注意没有多个文件一起下载的时候）

1在家里使用家庭宽带（联通200兆光纤，下载26mb/s,上传4mb/s）
2在公司使用公司宽带（电信千兆光纤，固定IP的企业专用宽带，下载120mb/s,上传120mb/s）

#### 问题描述：
下载了几个文件之后，就会遇到限速，单个文件下载，很多文件都速度在100kb/s以内，部分文件甚至是10kb/s以内或者长时间下载速度为0kb/s。此时在网页版直接点击下载按钮使用浏览器直接下载也是被限速的，浏览器下载速度也在100kb/s以内

因为下载链接本身就有时效，所以基本上几百兆的文件都无法下载了

在6pan博客看到有人攻击你们封IP了，所以我还在家尝试多次断开宽带重新拨号上网（为了换IP），在家挂VPN（为了换地区），到公司下载，多次尝试结果一致，都会频繁遇到下载限速

我得出了结论，并不是因为IP被错误屏蔽，就是简单的6盘开始限制免费账号的下载速度了

#### 使用环境：
网页版点击下载，复制下载链接，使用IDM下载，并设置IDM为5线程并发下载，一次只下载一个文件！（特别注意没有多个文件一起下载的时候）

1在家里使用家庭宽带（联通200兆光纤，下载26mb/s,上传4mb/s）
2在公司使用公司宽带（电信千兆光纤，固定IP的企业专用宽带，下载120mb/s,上传120mb/s）

#### 问题描述：
使用VIP账号登录后下载，
1 下载大文件时也会频繁遇到限速！！！！

比如我在家下载周杰伦演唱会.mp4,文件体积是15GB，开始下载时IDM是跑满的（5线程）(下载速度25-28mb/s)，下载到7GB左右时突然就没有速度了，下载失败，立即重新下载也没有速度。

多次尝试后发现必须要等1分钟左右，然后再重新下载，速度就恢复了（注意一直使用同一个下载链接，没有更换新的下载链接，不是链接超时导致的）。

然后以此循环，下载到14GB左右（又下载了7GB），速度突然为0，等待一分钟左右，才能重新下载，直到下载完

2 连续下载大量小文件时会频繁遇到限速！！！

比如我下载一个漫画合集，有300多期漫画.zip+300多封面.jpg，连续的下载时就频繁遇到下载突然没有速度，等一等才有速度

我总结了一下，感觉是你们对VIP账号有短时的流量限制（xx分钟内xxGB流量）或者是对VIP账号有短时访问次数限制（QPS）
我也尝试了一下https://github.com/Mrs4s/six-cli 表现一样，会遇到限速

### 请回复一下现在6盘现在的限速策略（免费用户和VIP用户都说一下具体的限速策略），我好按照你们的限速去设置IDM

不要说IP被误封，我试了，换IP，换地区，都不管用，该限速就是限速。你们限速了就应该说明白具体的限速策略，请不要推诿，我的提问很直白请正面回答

**Comment by liupan1890** [comment]
补充说明

1 我最近几天下载都遇到了限速，所以不是网络问题

2 我最近几天最多的一天是VIP账号下载了600+文件（300期漫画，共30GB）并没有大流量下载行为，也没有大批量下载行为

3 我最近几天最多的一天是连续下载了2小时，没有长期下载行为

**Comment by qingzhenyun** [comment]
目前的策略是这样的：

免费用户共享10个1Gbps端口，单IP限制为50Mbps，单IP不能同时超过8线程，无其他使用限制。

收费用户不限制速度，限制日总流量为10TB（以1000Mbps下行为例，这个限制几乎不可能达到，除非几台机器一起下载），但最好不要超过16线程。

不过在上周开始有两件事情，一个是目前有成批量、持续性的的攻击，noc人员错误操作封禁了CDN的 IP，导致一部分文件无法回源，因为CDN的IP 众多，且遍布全球，我们正在逐步解封。另一个是我们发现下载链接如果被分享（通常是无意的，比如被迅雷等软件抓取，会导致同一文件有大量线程，某些运营商出口只有一个IP）可能会触发防攻击系统，具体体现为 403封禁10分钟-1小时，针对这个问题是事先没有考虑到，目前正在逐步采用新的防攻击方式。
________________________________
发件人: liupan1890 <notifications@github.com>
发送时间: 2020年9月4日 21:26
收件人: qingzhenyun/qingzhenyun-api-doc <qingzhenyun-api-doc@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [qingzhenyun/qingzhenyun-api-doc] 请回复一下现在的限速策略 (#22)


请回复一下现在的限速策略

第一：我使用免费账号下载，遇到了极为严重的限速，基本上就是无法使用了
使用环境：

网页版点击下载，复制下载链接，使用IDM下载，并设置IDM为5线程并发下载，一次只下载一个文件！（特别注意没有多个文件一起下载的时候）

1在家里使用家庭宽带（联通200兆光纤，下载26mb/s,上传4mb/s）
2在公司使用公司宽带（电信千兆光纤，固定IP的企业专用宽带，下载120mb/s,上传120mb/s）

问题描述：

下载了几个文件之后，就会遇到限速，单个文件下载，很多文件都速度在100kb/s以内，部分文件甚至是10kb/s以内或者长时间下载速度为0kb/s。此时在网页版直接点击下载按钮使用浏览器直接下载也是被限速的，浏览器下载速度也在100kb/s以内

因为下载链接本身就有时效，所以基本上几百兆的文件都无法下载了

在6pan博客看到有人攻击你们封IP了，所以我还在家尝试多次断开宽带重新拨号上网（为了换IP），在家挂VPN（为了换地区），到公司下载，多次尝试结果一致，都会频繁遇到下载限速

我得出了结论，并不是因为IP被错误屏蔽，就是简单的6盘开始限制免费账号的下载速度了

第二：我开通按月订阅的VIP账号下载，还是会遇到限速，下载大文件或者连续下载多个小文件都会遇到限速，体验很不好
使用环境：

网页版点击下载，复制下载链接，使用IDM下载，并设置IDM为5线程并发下载，一次只下载一个文件！（特别注意没有多个文件一起下载的时候）

1在家里使用家庭宽带（联通200兆光纤，下载26mb/s,上传4mb/s）
2在公司使用公司宽带（电信千兆光纤，固定IP的企业专用宽带，下载120mb/s,上传120mb/s）

问题描述：

使用VIP账号登录后下载，
1 下载大文件时也会频繁遇到限速！！！！

比如我在家下载周杰伦演唱会.mp4,文件体积是15GB，开始下载时IDM是跑满的（5线程）(下载速度25-28mb/s)，下载到7GB左右时突然就没有速度了，下载失败，立即重新下载也没有速度。

多次尝试后发现必须要等1分钟左右，然后再重新下载，速度就恢复了（注意一直使用同一个下载链接，没有更换新的下载链接，不是链接超时导致的）。

然后以此循环，下载到14GB左右（又下载了7GB），速度突然为0，等待一分钟左右，才能重新下载，直到下载完

2 连续下载大量小文件时会频繁遇到限速！！！

比如我下载一个漫画合集，有300多期漫画.zip+300多封面.jpg，连续的下载时就频繁遇到下载突然没有速度，等一等才有速度

我总结了一下，感觉是你们对VIP账号有短时的流量限制（xx分钟内xxGB流量）或者是对VIP账号有短时访问次数限制（QPS）
我也尝试了一下https://github.com/Mrs4s/six-cli 表现一样，会遇到限速

请回复一下现在6盘现在的限速策略（免费用户和VIP用户都说一下具体的限速策略），我好按照你们的限速去设置IDM

不要说IP被误封，我试了，换IP，换地区，都不管用，该限速就是限速。你们限速了就应该说明白具体的限速策略，请不要推诿，我的提问很直白请正面回答

―

**Comment by qingzhenyun** [comment]
截图为我们近期非会员出口的流量目前确实比较拥堵。近期如果可能的话我们会加大采购量。
________________________________
发件人: 清真 云 <qingzhenyun@hotmail.com>
发送时间: 2020年9月6日 10:45
收件人: qingzhenyun/qingzhenyun-api-doc <qingzhenyun-api-doc@noreply.github.com>; qingzhenyun/qingzhenyun-api-doc <reply@reply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复: [qingzhenyun/qingzhenyun-api-doc] 请回复一下现在的限速策略 (#22)

目前的策略是这样的：

免费用户共享10个1Gbps端口，单IP限制为50Mbps，单IP不能同时超过8线程，无其他使用限制。

收费用户不限制速度，限制日总流量为10TB（以1000Mbps下行为例，这个限制几乎不可能达到，除非几台机器一起下载），但最好不要超过16线程。

不过在上周开始有两件事情，一个是目前有成批量、持续性的的攻击，noc人员错误操作封禁了CDN的 IP，导致一部分文件无法回源，因为CDN的IP 众多，且遍布全球，我们正在逐步解封。另一个是我们发现下载链接如果被分享（通常是无意的，比如被迅雷等软件抓取，会导致同一文件有大量线程，某些运营商出口只有一个IP）可能会触发防攻击系统，具体体现为 403封禁10分钟-1小时，针对这个问题是事先没有考虑到，目前正在逐步采用新的防攻击方式。
________________________________
发件人: liupan1890 <notifications@github.com>
发送时间: 2020年9月4日 21:26
收件人: qingzhenyun/qingzhenyun-api-doc <qingzhenyun-api-doc@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [qingzhenyun/qingzhenyun-api-doc] 请回复一下现在的限速策略 (#22)


请回复一下现在的限速策略

第一：我使用免费账号下载，遇到了极为严重的限速，基本上就是无法使用了
使用环境：

网页版点击下载，复制下载链接，使用IDM下载，并设置IDM为5线程并发下载，一次只下载一个文件！（特别注意没有多个文件一起下载的时候）

1在家里使用家庭宽带（联通200兆光纤，下载26mb/s,上传4mb/s）
2在公司使用公司宽带（电信千兆光纤，固定IP的企业专用宽带，下载120mb/s,上传120mb/s）

问题描述：

下载了几个文件之后，就会遇到限速，单个文件下载，很多文件都速度在100kb/s以内，部分文件甚至是10kb/s以内或者长时间下载速度为0kb/s。此时在网页版直接点击下载按钮使用浏览器直接下载也是被限速的，浏览器下载速度也在100kb/s以内

因为下载链接本身就有时效，所以基本上几百兆的文件都无法下载了

在6pan博客看到有人攻击你们封IP了，所以我还在家尝试多次断开宽带重新拨号上网（为了换IP），在家挂VPN（为了换地区），到公司下载，多次尝试结果一致，都会频繁遇到下载限速

我得出了结论，并不是因为IP被错误屏蔽，就是简单的6盘开始限制免费账号的下载速度了

第二：我开通按月订阅的VIP账号下载，还是会遇到限速，下载大文件或者连续下载多个小文件都会遇到限速，体验很不好
使用环境：

网页版点击下载，复制下载链接，使用IDM下载，并设置IDM为5线程并发下载，一次只下载一个文件！（特别注意没有多个文件一起下载的时候）

1在家里使用家庭宽带（联通200兆光纤，下载26mb/s,上传4mb/s）
2在公司使用公司宽带（电信千兆光纤，固定IP的企业专用宽带，下载120mb/s,上传120mb/s）

问题描述：

使用VIP账号登录后下载，
1 下载大文件时也会频繁遇到限速！！！！

比如我在家下载周杰伦演唱会.mp4,文件体积是15GB，开始下载时IDM是跑满的（5线程）(下载速度25-28mb/s)，下载到7GB左右时突然就没有速度了，下载失败，立即重新下载也没有速度。

多次尝试后发现必须要等1分钟左右，然后再重新下载，速度就恢复了（注意一直使用同一个下载链接，没有更换新的下载链接，不是链接超时导致的）。

然后以此循环，下载到14GB左右（又下载了7GB），速度突然为0，等待一分钟左右，才能重新下载，直到下载完

2 连续下载大量小文件时会频繁遇到限速！！！

比如我下载一个漫画合集，有300多期漫画.zip+300多封面.jpg，连续的下载时就频繁遇到下载突然没有速度，等一等才有速度

我总结了一下，感觉是你们对VIP账号有短时的流量限制（xx分钟内xxGB流量）或者是对VIP账号有短时访问次数限制（QPS）
我也尝试了一下https://github.com/Mrs4s/six-cli 表现一样，会遇到限速

请回复一下现在6盘现在的限速策略（免费用户和VIP用户都说一下具体的限速策略），我好按照你们的限速去设置IDM

不要说IP被误封，我试了，换IP，换地区，都不管用，该限速就是限速。你们限速了就应该说明白具体的限速策略，请不要推诿，我的提问很直白请正面回答

―

**Comment by qingzhenyun** [comment]
根据技术部门刚刚的反馈，防攻击策略目前存在问题，当一个IP的连接数到达上限之后直接封禁1小时，这个方式比较粗暴。上班之后技术部门会做出调整。
________________________________
发件人: 清真 云 <qingzhenyun@hotmail.com>
发送时间: 2020年9月6日 10:57
收件人: qingzhenyun/qingzhenyun-api-doc <qingzhenyun-api-doc@noreply.github.com>; qingzhenyun/qingzhenyun-api-doc <reply@reply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复: [qingzhenyun/qingzhenyun-api-doc] 请回复一下现在的限速策略 (#22)

截图为我们近期非会员出口的流量目前确实比较拥堵。近期如果可能的话我们会加大采购量。
________________________________
发件人: 清真 云 <qingzhenyun@hotmail.com>
发送时间: 2020年9月6日 10:45
收件人: qingzhenyun/qingzhenyun-api-doc <qingzhenyun-api-doc@noreply.github.com>; qingzhenyun/qingzhenyun-api-doc <reply@reply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复: [qingzhenyun/qingzhenyun-api-doc] 请回复一下现在的限速策略 (#22)

目前的策略是这样的：

免费用户共享10个1Gbps端口，单IP限制为50Mbps，单IP不能同时超过8线程，无其他使用限制。

收费用户不限制速度，限制日总流量为10TB（以1000Mbps下行为例，这个限制几乎不可能达到，除非几台机器一起下载），但最好不要超过16线程。

不过在上周开始有两件事情，一个是目前有成批量、持续性的的攻击，noc人员错误操作封禁了CDN的 IP，导致一部分文件无法回源，因为CDN的IP 众多，且遍布全球，我们正在逐步解封。另一个是我们发现下载链接如果被分享（通常是无意的，比如被迅雷等软件抓取，会导致同一文件有大量线程，某些运营商出口只有一个IP）可能会触发防攻击系统，具体体现为 403封禁10分钟-1小时，针对这个问题是事先没有考虑到，目前正在逐步采用新的防攻击方式。
________________________________
发件人: liupan1890 <notifications@github.com>
发送时间: 2020年9月4日 21:26
收件人: qingzhenyun/qingzhenyun-api-doc <qingzhenyun-api-doc@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [qingzhenyun/qingzhenyun-api-doc] 请回复一下现在的限速策略 (#22)


请回复一下现在的限速策略

第一：我使用免费账号下载，遇到了极为严重的限速，基本上就是无法使用了
使用环境：

网页版点击下载，复制下载链接，使用IDM下载，并设置IDM为5线程并发下载，一次只下载一个文件！（特别注意没有多个文件一起下载的时候）

1在家里使用家庭宽带（联通200兆光纤，下载26mb/s,上传4mb/s）
2在公司使用公司宽带（电信千兆光纤，固定IP的企业专用宽带，下载120mb/s,上传120mb/s）

问题描述：

下载了几个文件之后，就会遇到限速，单个文件下载，很多文件都速度在100kb/s以内，部分文件甚至是10kb/s以内或者长时间下载速度为0kb/s。此时在网页版直接点击下载按钮使用浏览器直接下载也是被限速的，浏览器下载速度也在100kb/s以内

因为下载链接本身就有时效，所以基本上几百兆的文件都无法下载了

在6pan博客看到有人攻击你们封IP了，所以我还在家尝试多次断开宽带重新拨号上网（为了换IP），在家挂VPN（为了换地区），到公司下载，多次尝试结果一致，都会频繁遇到下载限速

我得出了结论，并不是因为IP被错误屏蔽，就是简单的6盘开始限制免费账号的下载速度了

第二：我开通按月订阅的VIP账号下载，还是会遇到限速，下载大文件或者连续下载多个小文件都会遇到限速，体验很不好
使用环境：

网页版点击下载，复制下载链接，使用IDM下载，并设置IDM为5线程并发下载，一次只下载一个文件！（特别注意没有多个文件一起下载的时候）

1在家里使用家庭宽带（联通200兆光纤，下载26mb/s,上传4mb/s）
2在公司使用公司宽带（电信千兆光纤，固定IP的企业专用宽带，下载120mb/s,上传120mb/s）

问题描述：

使用VIP账号登录后下载，
1 下载大文件时也会频繁遇到限速！！！！

比如我在家下载周杰伦演唱会.mp4,文件体积是15GB，开始下载时IDM是跑满的（5线程）(下载速度25-28mb/s)，下载到7GB左右时突然就没有速度了，下载失败，立即重新下载也没有速度。

多次尝试后发现必须要等1分钟左右，然后再重新下载，速度就恢复了（注意一直使用同一个下载链接，没有更换新的下载链接，不是链接超时导致的）。

然后以此循环，下载到14GB左右（又下载了7GB），速度突然为0，等待一分钟左右，才能重新下载，直到下载完

2 连续下载大量小文件时会频繁遇到限速！！！

比如我下载一个漫画合集，有300多期漫画.zip+300多封面.jpg，连续的下载时就频繁遇到下载突然没有速度，等一等才有速度

我总结了一下，感觉是你们对VIP账号有短时的流量限制（xx分钟内xxGB流量）或者是对VIP账号有短时访问次数限制（QPS）
我也尝试了一下https://github.com/Mrs4s/six-cli 表现一样，会遇到限速

请回复一下现在6盘现在的限速策略（免费用户和VIP用户都说一下具体的限速策略），我好按照你们的限速去设置IDM

不要说IP被误封，我试了，换IP，换地区，都不管用，该限速就是限速。你们限速了就应该说明白具体的限速策略，请不要推诿，我的提问很直白请正面回答

―

**Comment by liupan1890** [comment]
非常感谢您的回复

### 免费账号
1 免费用户单IP不能同时超过8线程

我感觉你们对单IP同时线程数统计的有问题，同时我们理解上当然是同一时间--毫秒，实际上因为是cdn，估计统计的精度不够，比如实际上是统计的5秒内不能超过8线程？？总感觉根本没到8线程（我都是设置的5线程）就会触发。

我想你们是否可以检查一下设置，如果精度不够（例如排队下载时，9点15分11秒正在下载001.rar,刚好下完了，9点15分12秒开始下载002.rar，也就是2秒内统计会有10线程），那会造成误报

2 单IP限制为50Mbps

我经常遇到长时间下载速度是《100kb/s这样的（重新下载一个新文件也还是100kb/s）,达不到5MB/s的速度

#### 不过这也不重要，我开了VIP了，以后也会一直开下去，一个月10块真的良心价了，只要以后别随意涨价，会一直支持的


### VIP账号

1 最好不要超过16线程

所以说VIP还是有并发限制的，只是随着“攻击”情况可能在动态调整？

2 我遇到的7GB断流问题呢？

我遇到的下载大文件时，每下载7GB就出现下载中断并且要等一混才能重新开始继续下载的问题，您没有处理哦？？
因为我的下载速度是26MB/s,也就是每下载4分钟左右就会出现强制断流，下载失败。要等一分钟后（估值），才能继续下载。这是为什么？

VIP，单文件，5线程，下载15GB的文件，要被中断2次！！
（注意并不需要更换新的下载地址，就是一个下载地址，重新下载3次才能下完）
（注意并不是我网络问题，因为我用迅雷，百度网盘，IDM下载其他资源并没有遇到过，只是下载6盘内文件遇到了）

#### 请帮我检查一下7GB断流问题，这个下载体验太差了，等于必须一直盯着下载不能离开（不知道什么时候就断流了）

**Comment by qingzhenyun** [comment]
以下是技术部门回复：


1 免费用户单IP不能同时超过8线程，且速度无法达到预期

 免费用户的CDN和收费用户是隔离的，现在一是免费用户的CDN日常处于24小时满载状态，等于一个天然的限速，这边需要我们加大采购力度才能解决，另外之前误操作将免费用户的CDN当作了普通用户，导致CDN的IP被封禁






---------------------------

>>

所以说VIP还是有并发限制的，只是随着“攻击”情况可能在动态调整？

VIP 未限制网速，但是对并发频率之类的确实会存在限制。现阶段主要是防攻击系统错误动作比较频繁和粗暴，作为一家非互联网企业，这方面我们还是需要多学习互联网场上的做法。

>> 因为我的下载速度是26MB/s,也就是每下载4分钟左右就会出现强制断流，下载失败。要等一分钟后（估值），才能继续下载。这是为什么？

这个速度看起来问题不是在CDN 这个我们猜测是三个可能性，
1、防攻击模块错误动作；
2、文件分片组合失败，后端实际上已经报错，需要等文件从其他节点拉取数据。
3、该文件被识别为版权/色情，系统将其存储在海外，下载的时候遭遇了Connection Reset，前端服务器等待IP切换（俗称撞墙）

我们需要更多的信息才能确认，能否提供一个下载地址以供我们进一步分析？
________________________________
发件人: liupan1890 <notifications@github.com>
发送时间: 2020年9月7日 9:40
收件人: qingzhenyun/qingzhenyun-api-doc <qingzhenyun-api-doc@noreply.github.com>
抄送: qingzhenyun <qingzhenyun@hotmail.com>; Comment <comment@noreply.github.com>
主题: Re: [qingzhenyun/qingzhenyun-api-doc] 请回复一下现在的限速策略 (#22)


非常感谢您的回复

免费账号

1 免费用户单IP不能同时超过8线程

我感觉你们对单IP同时线程数统计的有问题，同时我们理解上当然是同一时间--毫秒，实际上因为是cdn，估计统计的精度不够，比如实际上是统计的5秒内不能超过8线程？？总感觉根本没到8线程（我都是设置的5线程）就会触发。

我想你们是否可以检查一下设置，如果精度不够（例如排队下载时，9点15分11秒正在下载001.rar,刚好下完了，9点15分12秒开始下载002.rar，也就是2秒内统计会有10线程），那会造成误报

2 单IP限制为50Mbps

我经常遇到长时间下载速度是《100kb/s这样的（重新下载一个新文件也还是100kb/s）,达不到5MB/s的速度

不过这也不重要，我开了VIP了，以后也会一直开下去，一个月10块真的良心价了，只要以后别随意涨价，会一直支持的
VIP账号

1 最好不要超过16线程

所以说VIP还是有并发限制的，只是随着“攻击”情况可能在动态调整？

2 我遇到的7GB断流问题呢？

我遇到的下载大文件时，每下载7GB就出现下载中断并且要等一混才能重新开始继续下载的问题，您没有处理哦？？
因为我的下载速度是26MB/s,也就是每下载4分钟左右就会出现强制断流，下载失败。要等一分钟后（估值），才能继续下载。这是为什么？

VIP，单文件，5线程，下载15GB的文件，要被中断2次！！
（注意并不需要更换新的下载地址，就是一个下载地址，重新下载3次才能下完）
（注意并不是我网络问题，因为我用迅雷，百度网盘，IDM下载其他资源并没有遇到过，只是下载6盘内文件遇到了）

请帮我检查一下7GB断流问题，这个下载体验太差了，等于必须一直盯着下载不能离开（不知道什么时候就断流了）

―

**Comment by liupan1890** [comment]
https://s1.ax1x.com/2020/09/07/wucz4g.gif
https://s1.ax1x.com/2020/09/07/wucxUS.png

看到回复我又去要测试了一次，如上面截图所示，我用Fiddler抓包调试后确认，是触发了访问限制（VIP账号，并发数限制）。出错时是返回简单的502应答


所以就是因为文件分片下载+网速，造成短时间内多次206下载请求时会很容易的就触发并发数限制（请看截图，确实是5线程并发下载的）


所以证实了我的推论，你们的并发数限制并不只是限制同时连接数8，还有N分钟内允许请求XX次的这种访问次数限制（常见于cc防御），


我的网速是26MB/s,分片体积21MB,5线程并发，也就是1分钟内会有75次访问.
因为会触发限速，以此推论你们应该设置的是1分钟80次访问或5分钟300次访问的限制！
又因为我每次都是大概7GB，也就是大概5分钟会被限制，大概率是5分钟300次访问的限制！


你们这样设置并不合理，你们应该区分出我300次访问是对同一个文件的断点续传还是对不同文件的访问。
如果是同一文件断点续传就不应该限制。
如果是访问多个文件才可以按照你们的规划去限制！


最后你们现在的这种限制我只能通过浏览器去下载，因为大部分下载软件只能设置并发数，不能设置分片大小。
而一旦遇到我网速快++分片小时就会触发你们的限制导致下载失败，体验很不好，
因为你不知道什么时候就会触发下载失败（网速+分片+并发多因素导致）。
哪怕是你们把触发限速后调整为**限速**而不是直接502也好，最起码不会下载失败，
我现在只要下载大文件就要一直盯着，不盯就失败。超时就要重新获取新的下载链接完全重新下载。死循环。
浏览器又不能按顺序单文件下载，会多文件一起下，还是会触发限速。

总之就是盯着盯着盯着，可以下，想要让他自己下不管他就不行。这是什么体验，你自己试试

**Comment by liupan1890** [comment]
![录像](https://ftp.bmp.ovh/imgs/2020/09/2c7feb1981d3eedb.gif)

**Comment by qingzhenyun** [comment]
以下是技术部门反馈：
502 估计不是单纯的CC防御模块，可能还涉及到底层RPC调用的限制（API网关自身也有熔断机制），这一块我们已经反馈到相关人员，目前的防御策略确实相对简单粗暴，不过进行合理的调整可能需要一定时间。因为防攻击平台中间参数相对较多，目前只能一点点测试，一下子放开容易导致我们源站被迅雷等盗链软件击垮，设置太严格又会导致不必要的用户被限制。再次感谢您的关注。
________________________________
发件人: liupan1890 <notifications@github.com>
发送时间: 2020年9月7日 17:33
收件人: qingzhenyun/qingzhenyun-api-doc <qingzhenyun-api-doc@noreply.github.com>
抄送: qingzhenyun <qingzhenyun@hotmail.com>; Comment <comment@noreply.github.com>
主题: Re: [qingzhenyun/qingzhenyun-api-doc] 请回复一下现在的限速策略 (#22)


https://s1.ax1x.com/2020/09/07/wucz4g.gif
https://s1.ax1x.com/2020/09/07/wucxUS.png

看到回复我又去要测试了一次，如上面截图所示，我用Fiddler抓包调试后确认，是触发了访问限制（VIP账号，并发数限制）。出错时是返回简单的502应答

所以就是因为文件分片下载+网速，造成短时间内多次206下载请求时会很容易的就触发并发数限制（请看截图，确实是5线程并发下载的）

所以证实了我的推论，你们的并发数限制并不只是限制同时连接数8，还有N分钟内允许请求XX次的这种访问次数限制（常见于cc防御），

我的网速是26MB/s,分片体积21MB,5线程并发，也就是1分钟内会有75次访问.
因为会触发限速，以此推论你们应该设置的是1分钟80次访问或5分钟300次访问的限制！
又因为我每次都是大概7GB，也就是大概5分钟会被限制，大概率是5分钟300次访问的限制！

你们这样设置并不合理，你们应该区分出我300次访问是对同一个文件的断点续传还是对不同文件的访问。
如果是同一文件断点续传就不应该限制。
如果是访问多个文件才可以按照你们的规划去限制！

最后你们现在的这种限制我只能通过浏览器去下载，因为大部分下载软件只能设置并发数，不能设置分片大小。
而一旦遇到我网速快++分片小时就会触发你们的限制导致下载失败，体验很不好，
因为你不知道什么时候就会触发下载失败（网速+分片+并发多因素导致）。
哪怕是你们把触发限速后调整为限速而不是直接502也好，最起码不会下载失败，
我现在只要下载大文件就要一直盯着，不盯就失败。超时就要重新获取新的下载链接完全重新下载。死循环。
浏览器又不能按顺序单文件下载，会多文件一起下，还是会触发限速。

总之就是盯着盯着盯着，可以下，想要让他自己下不管他就不行。这是什么体验，你自己试试

―

**Comment by qingzhenyun** [comment]
我又仔细看了下您的截图，这个域名在您测试的时候是已经放开了连接数限制（如果被限制，应该是返回403状态码），502的情况可能是源站已经被打垮了。
能否告知我们您测试的大致时间，我们可能需要找源站方向排查文通。
________________________________
发件人: liupan1890 <notifications@github.com>
发送时间: 2020年9月7日 17:41
收件人: qingzhenyun/qingzhenyun-api-doc <qingzhenyun-api-doc@noreply.github.com>
抄送: qingzhenyun <qingzhenyun@hotmail.com>; Comment <comment@noreply.github.com>
主题: Re: [qingzhenyun/qingzhenyun-api-doc] 请回复一下现在的限速策略 (#22)


[录像]<https://camo.githubusercontent.com/69b76636aee7ea198f61328789871680d266376e/68747470733a2f2f6674702e626d702e6f76682f696d67732f323032302f30392f326337666562313938316433656564622e676966>

―

**Comment by liupan1890** [comment]
再次感谢一下您的耐心回复，时间大概就是贴图的时间，截完图我就发上来了

1 我只是26MB/s的家庭宽带啊（联通200M光纤），城市已经普及了

2 正常使用浏览器是没问题的可以正常下载

3 只有我21M一个分片，5线程分片下载时才会遇到5分钟断网问题

4 根下载哪一个文件无关，根文件大小也关系不大（大于8GB即可触发）

5 我现在切换到调用aria下载了，aria可以设置最小分片体积，我设置为200MB，没有出现任何问题了

正您所说，

“不过进行合理的调整可能需要一定时间。因为防攻击平台中间参数相对较多，目前只能一点点测试”

我没事了，顺祝商祺
