### ISSUE TITLE
回收站内文件还原BUG

### ISSUE THREAD

**Issue by liupan1890** [qingzhenyun/qingzhenyun-api-doc#25]
测试用例：

在网盘根目录有一个文件夹，文件夹内有多个文件。例如：
``````
/文件夹001
/文件夹001/文件名.txt
/文件夹001/另外一个文件.txt
/文件夹001/一个视频.mp4
``````

1. 第一步，删除/文件夹001/一个视频.mp4
2. 第二步，删除/文件夹001
3. 第三步，在回收站还原/文件夹001/一个视频.mp4
4. 第四步，在回收站还原/文件夹001

预期结果：文件会按照原来的目录正确恢复
实际执行结果：文件名变更为数字

预期
``````
/文件夹001
/文件夹001/文件名.txt
/文件夹001/另外一个文件.txt
/文件夹001/一个视频.mp4
``````

实际1
``````
/文件夹001
/文件夹001/文件名.txt
/文件夹001/另外一个文件.txt
/文件夹001/bv2actk8n51no5fn0lt0.mp4
``````

实际2 (第3步，和第4步顺序颠倒)
``````
/文件夹001
/文件夹001/文件名.txt
/文件夹001/另外一个文件.txt
/文件夹001/bv2actk8n51no5fn0lt0/一个视频.mp4
``````

**Comment by qingzhenyun** [comment]
已经将问题反馈技术，等待技术回复。
目前技术有抽调去其他项目组，可能需要较长时间才能修复。

http://192.168.100.231/tp/csr/dashboard?ticketId=93291&projectId=92

________________________________
发件人: liupan1890 <notifications@github.com>
发送时间: 2020年11月30日 16:06
收件人: qingzhenyun/qingzhenyun-api-doc <qingzhenyun-api-doc@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [qingzhenyun/qingzhenyun-api-doc] 回收站内文件还原BUG (#25)


测试用例：

在网盘根目录有一个文件夹，文件夹内有多个文件。例如：

/文件夹001
/文件夹001/文件名.txt
/文件夹001/另外一个文件.txt
/文件夹001/一个视频.mp4


  1.  第一步，删除/文件夹001/一个视频.mp4
  2.  第二步，删除/文件夹001
  3.  第三步，在回收站还原/文件夹001/一个视频.mp4
  4.  第四步，在回收站还原/

预期结果：文件会按照原来的目录正确恢复
实际执行结果：文件名变更为数字

预期

/文件夹001
/文件夹001/文件名.txt
/文件夹001/另外一个文件.txt
/文件夹001/一个视频.mp4


实际1

/文件夹001
/文件夹001/文件名.txt
/文件夹001/另外一个文件.txt
/文件夹001/bv2actk8n51no5fn0lt0.mp4


实际2

/文件夹001
/文件夹001/文件名.txt
/文件夹001/另外一个文件.txt
/文件夹001/bv2actk8n51no5fn0lt0/一个视频.mp4


―

**Comment by liupan1890** [comment]
好的，这是一个比较久远的bug了。。。。
